### PR TITLE
Redirect to HTTPS without a trailing slash

### PR DESCRIPTION
**Pull request by umireon**
The mod_dir redirects https://example.com/admin to http://example.com/admin/ when the apache is behind an HTTPS reverse proxy because the Location header requires the scheme and the apache didn't consider X-Forwarded-Proto.

This rewrite rule in this htaccess will add a trailing slash with the correct scheme.

Ref: https://serverfault.com/a/851918
Ref: https://stackoverflow.com/a/40447815

`%{LA-U:REQUEST_FILENAME}` will access the server via mod_dir and check if the resulted URL is a directory.

### CODE REVIEW

**Comment by umireon** [comment]
Fixed

**Comment by LeoColomb** [comment]
Thanks for opening this PR, @umireon!
That said I am not sure to understand the need.
Have you experienced the issue?
Have you setup your YOURLS config correctly?

**Comment by umireon** [comment]
@LeoColomb I experienced this issue. The issue is that apache ignores HTTPS termination on my reverse proxy. 
I am using traefik as my reverse proxy.
The following is the simplified docker-compose.yml I am using.

```yaml
version: '3.9'

services:
  traefik:
    image: 'traefik:v2.5'
    restart: 'always'
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.traefik.address=:3000'
      - '--certificatesresolvers.myresolver.acme.dnschallenge=true'
      - '--certificatesresolvers.myresolver.acme.dnschallenge.provider=gcloud'
      - '--certificatesresolvers.myresolver.acme.email=root@example.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '443:443'
      - '3000:3000'
    environment:
      - 'GCE_PROJECT=example'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/letsencrypt/example.json'
    volumes:
      - '/share/letsencrypt:/letsencrypt'
      - 'traefik:/traefik'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    extra_hosts:
      - 'gateway.docker.internal:host-gateway'
 
  yourls:
    image: 'yourls'
    restart: 'always'
    volumes:
      - '/share/yourls:/var/www/html/user'
    environment:
      'YOURLS_DB_PASS': 'supersecret'
      'YOURLS_SITE': 'https://example.com'
      'YOURLS_USER': 'admin'
      'YOURLS_PASS': 'admin'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.yourls.rule=Host(`example.com`)'
      - 'traefik.http.routers.yourls.service=yourls'
      - 'traefik.http.routers.yourls.tls.certresolver=myresolver'
      - 'traefik.http.routers.yourls.tls.domains[0].main=example.com'
      - 'traefik.http.services.yourls.loadbalancer.server.port=80'
  
  mysql:
    image: 'mysql:5.7'
    restart: 'always'
    volumes:
      - '/share/mysql/data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'supersecret'
      MYSQL_ROOT_HOST: '%'
```

**Comment by umireon** [comment]
@LeoColomb I'm sorry that my description of this PR was wrong. I've added the trailing slash to the resulted URL.
The change is as follows:

From:

> The mod_dir redirects https://example.com/admin to http://example.com/admin when

To:

> The mod_dir redirects https://example.com/admin to http://example.com/admin/ when

**Comment by LeoColomb** [comment]
I am honestly not very keen to accept these additions.
Indeed, I don't see any other popular Docker image that includes this workaround.
Why would YOURLS image need this and [not the WordPress one](https://github.com/docker-library/wordpress/blob/9954966feffdaf39082609816f896c2e3f75f0db/latest/php8.0/apache/Dockerfile#L121-L131)?

**Comment by umireon** [comment]
Then I will propose this to WordPress one.

**Comment by umireon** [comment]
https://github.com/docker-library/wordpress/pull/640

**Comment by LeoColomb** [comment]
I'm going to close this pull request.
Two things are suggested before reconsidering this change:
* First, WordPress community approval on the same change;
* Then location of the change, as it probably makes sense to submit it to upstream YOURLS/YOURLS project instead.

**Pull request closed without merging**
