### PR TITLE
Add support for `docker`

### PR DESCRIPTION
**Pull request by kamilzabielski**
This patch is a continuation of:
* https://github.com/YOURLS/YOURLS/pull/2315

It adds support for YOURL-s Docker image.

Signed-off-by: Zabielski, Kamil <kamil.zabielski@outlook.com>

### CODE REVIEW

**Comment by ozh** [comment]
Thanks for opening things up :)

I'm not using Docker myself, so maybe stupid questions: 
- isn't there a way to avoid duplicating the config?
- any reason you're "gitmoduling" your YOURLS fork instead of the main repo?

**Comment by kamilzabielski** [comment]
@ozh: Awesome questions.

* There is no need to duplicate configuration file as long as YOURL's one will honour environment variables, as it is the most common way of exposing configuration into Docker container.
You can modify `sample-config.php` into my example; that will solve the issue of configuration duplication.

* Good review is a good point.
I fixed a submodule path for `/src/`.

**Comment by kamilzabielski** [comment]
@ozh 

Few more points:
* I will add myself as a maintainer of this image, how about it?

* I would like to avoid code duplication as well.
Can't we use my sample as main sample?

* Be so kind and create an image on `hub.docker.com` with `YOURLS` organisation.

**Comment by ozh** [comment]
I've created https://hub.docker.com/u/yourls/ and a team with you inside. I have no idea what to do next. This site requires that usernames be at least 4 chars long. I cannot go with "ozh". I hate this site. :)

No problem with you being a maintainer, as long as it allows any other interested user in contributing to this image, discuss choices, submit PR, etc..

Regarding code duplication : the goal would be, if possible, that this docker image doesn't mostly replicate YOURLS' config file. But I'm not adding in YOURLS config file what Docker would need regarding env vars: 99% of YOURLS users won't use them

**Comment by kamilzabielski** [comment]
@ozh 
* In case of character limitations; same problems everywhere. :-)
Thanks for being added.

Actually, it does not impact other users.
* My proposal uses ternary operator, so, if environment variable is not set, the value from configuration file is taken. For most deployments, I don't think people will expose `YOURLS_*` environment variables thought `Apache` or `php-fpm` processes.

**Comment by ozh** [comment]
You cannot imagine how many emails I get with terribly basic support question about editing the config file, apparently editing `define('SOME_NAME', 'some value')` is already way beyond many user heads. So, ternary operator and functions to get vars from env and how do I define env vars and stuff, well, nope.

**Comment by kamilzabielski** [comment]
@ozh 
* Actually, I do have a list of proposals, already.
How about putting them into `issues`?

For configuration file duplication.
* Ok, so there is one more option. We can use simple shell script, like Datadog-agent does [[1]].
It copies sample of configuration file into proper location and makes list of `sed`-s accordingly to the provided environment variables.
Does this option fit your needs?

[1]: https://github.com/DataDog/docker-dd-agent/blob/master/entrypoint.sh

**Comment by ozh** [comment]
Sure, filing issues to discuss options seems fine

Regarding code duplication, my expressed need is just to keep things as easily manageable (for maintainers) and usable (for end user) as possible. Duplicating code can be easier to use than using a complex script. Not being a Docker user, I have no specific needs in this area. I'll let users speak :)

**Pull request merged**
